imageType:
  Original: {}  # 只使用原始图像，不使用滤波
  Wavelet: {}  # 添加小波变换特征
  LoG:         # 添加高斯拉普拉斯滤波特征
    sigma: [1.0, 3.0]

featureClass:
  firstorder:
    - Mean
    - Median 
    - Energy
    - Entropy
    - TotalEnergy    # 添加更多一阶特征
    - Skewness
    - Kurtosis
    - Variance
    - RootMeanSquared
  glcm:
    - Contrast
    - Correlation
    - JointEntropy
    - Homogeneity1   # 添加纹理特征
    - ClusterShade
    - ClusterProminence
  gldm:
    - GrayLevelNonUniformity
    - DependenceEntropy
    - DependenceNonUniformity
  glrlm:
    - GrayLevelNonUniformity
    - RunLengthNonUniformity
    - LongRunHighGrayLevelEmphasis
  shape2D:  # 使用2D形状特征代替3D
    - Perimeter
    - Area
    - MajorAxisLength  # 添加更多形态特征
    - MinorAxisLength
    - Eccentricity

setting:
  binWidth: 25
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: null
  normalize: False
  force2D: True  # 确保使用2D计算
  voxelArrayShift: 400  # 处理负值
